### ISSUE TITLE
Pixel4a環境だと時間割ページが落ちる

### ISSUE THREAD

**Issue by ByakkoMatsumiya** [yambaru-hackathon/Group-2#8]
多分サイズ周りの問題<br>
<img width="300" src="https://github.com/yambaru-hackathon/Group-2/assets/77813933/60a4b471-c367-4abc-a03a-a4a09b759834">

**Comment by raisu3141** [comment]
幅を画面サイズによって調整するようにし、縦にスクロールできるようにしました。
 #fix/timetable_pageブランチに修正後のコードを置いておくので、問題ないか確認お願いします。

**Comment by ByakkoMatsumiya** [comment]
サイズ設定は良さそう、ただ何故かまだ落ちるので、もしかしたらこっち側の環境の問題かもしれない
（com.google.android.gms.providerinstaller.dynamiteが無いだの言われる）
ちょっと色々見てみる

**Comment by ByakkoMatsumiya** [comment]
Continueさせれば動くからなんだかなぁという気持ちになりつつ、とりあえず保留で
